server {
    listen 80;
    server_name noxi-staging.swedencentral.cloudapp.azure.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name noxi-staging.swedencentral.cloudapp.azure.com;

    ssl_certificate /etc/letsencrypt/live/noxi-staging/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/noxi-staging/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /ws {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}