name: CD — Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    name: Build, Push & Deploy Production
    runs-on: ubuntu-latest
    environment: production # ← Déclenche l'approbation manuelle

    steps:
      - name: Copy files to prod VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_PROD_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml,monitoring/"
          target: "/app/noxi/"

      - name: Deploy to prod VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_PROD_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cloud-init status --wait || true

            # Créer le .env
            cat > /app/noxi/.env << EOF
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
            DB_HOST=db
            DB_PORT=3306
            ENVIRONMENT=prod
            EOF

            cd /app/noxi
            sudo docker compose -f docker-compose.prod.yml pull
            sudo docker compose -f docker-compose.prod.yml up -d
            sudo docker image prune -f
